export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as ClassesSection } from './ClassesSection'
export { default as ScheduleSection } from './ScheduleSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as FAQSection } from './FAQSection'
export { default as ContactSection } from './ContactSection'
export { default as AIChatWidget } from './AIChatWidget'
export { default as PageRenderer, defaultHomePage, classesPage, aboutPage, contactPage } from './PageRenderer'
